spring.application.name: betterreads-data-loader

datadump.location:
  author: /opt/lampp/htdocs/learn/casandra/test-authors.txt
  works: /opt/lampp/htdocs/learn/casandra/test-works.txt

spring:
  data:
    cassandra:
      keyspace-name: main
      username: ##<username>                
      password: #<secret>
      schema-action: recreate #create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s

datastax.astra:
  secure-connect-bundle: secure-connect.zip
  
astra.db:
  id: #<db-id>
  region: europe-west1  
  keyspace: main
  application.token: ##<token>
  
  
  
  
  